USE [master]
GO

/****** Object:  Database [DbSecimProje]    Script Date: 11.06.2024 11:56:43 ******/
CREATE DATABASE [DbSecimProje]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DbSecimProje', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DbSecimProje.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DbSecimProje_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DbSecimProje_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DbSecimProje].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DbSecimProje] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DbSecimProje] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DbSecimProje] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DbSecimProje] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DbSecimProje] SET ARITHABORT OFF 
GO

ALTER DATABASE [DbSecimProje] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DbSecimProje] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DbSecimProje] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DbSecimProje] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DbSecimProje] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DbSecimProje] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DbSecimProje] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DbSecimProje] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DbSecimProje] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DbSecimProje] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DbSecimProje] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DbSecimProje] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DbSecimProje] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DbSecimProje] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DbSecimProje] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DbSecimProje] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DbSecimProje] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DbSecimProje] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DbSecimProje] SET  MULTI_USER 
GO

ALTER DATABASE [DbSecimProje] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DbSecimProje] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DbSecimProje] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DbSecimProje] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DbSecimProje] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DbSecimProje] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DbSecimProje] SET QUERY_STORE = ON
GO

ALTER DATABASE [DbSecimProje] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [DbSecimProje] SET  READ_WRITE 
GO


